app/forms.py
# a form is required to accept
# email, password, submit button
from flask_wtf import FlaskForm
from wtforms import (
    DateTimeLocalField,
    EmailField,
    FloatField,
    PasswordField,
    SubmitField,
    TextAreaField,
)
from wtforms.validators import DataRequired, Email, Length, NumberRange


class AuthForm(FlaskForm):
    email = EmailField(
        "Email",
        validators=(
            DataRequired("Email is required"),
            Email("Please enter valid email"),
        ),
    )
    password = PasswordField(
        "Passowrd",
        validators=[
            DataRequired("Password field can't be empty"),
            Length(min=8, message="Password length should be minium 8 characters"),
        ],
    )
    submit = SubmitField("Submit")


class NewStatementForm(FlaskForm):
    amount = FloatField(
        "Enter amount",
        [
            DataRequired("Amount is required!"),
            NumberRange(
                0.0001,
                9999999999.99,
                "Entered amount could not be added to your statement!",
            ),
        ],
    )
    description = TextAreaField(
        "Enter description",
        [
            DataRequired("Description is required!"),
            Length(5, 180, "Description can contain 5 to 180 characters!"),
        ],
        render_kw={"class": "textarea-h", "rows": "2"},
    )

    datetime_data = DateTimeLocalField(
        format="%Y-%m-%dT%H:%M", validators=[DataRequired("This field is required!")]
    )

    expense = SubmitField("Add Expense")
    income = SubmitField("Add Income")

app/__init__.py
import datetime
import os

from flask import Flask, Response, request
from flask_migrate import Migrate
from user_agents import parse

from app.commands import create_admin_user
from app.db import VisitorStats, db

migrate = Migrate(render_as_batch=True)


def create_app():
    app = Flask(__name__)

    app.config["SECRET_KEY"] = os.environ.get("SECRET_KEY", "NOTHING_IS_SECRET")
    app.config["SQLALCHEMY_DATABASE_URI"] = os.environ.get(
        "DB_URI", "sqlite:///master.sqlite3"
    )
    app.config["PERMANENT_SESSION_LIFETIME"] = datetime.timedelta(days=7)

    db.init_app(app)
    migrate.init_app(app, db, render_as_batch=True)
    with app.app_context():
        db.create_all()

    @app.after_request
    def after_request_(response: Response):  # type: ignore
        if request.endpoint != "static":
            response.headers["Cache-Control"] = "no-cache, no-store, must-revalidate"
        return response

    @app.before_request
    def app_before_data():  # type: ignore
        if request.endpoint != "static":
            user_agent = parse(request.user_agent.string)
            browser = user_agent.browser.family  # type: ignore
            device = user_agent.get_device()
            operating_system = user_agent.get_os()
            bot = user_agent.is_bot

            stat = VisitorStats(  # type: ignore
                browser=browser,
                device=device,
                operating_system=operating_system,
                is_bot=bot,
            )
            db.session.add(stat)
            db.session.commit()

    from app.views.admin import admin
    from app.views.auth import auth
    from app.views.home import home
    from app.views.settings import settings

    # request.blueprint != admin.name and
    blueprints = [auth, home, settings, admin]
    for bp in blueprints:
        app.register_blueprint(bp)

    # app.cli.add_command(create_admin_user)
    return app

app/views/admin.py
# requirements: all users, add user, remove user, see transactions of a user
from flask import Blueprint

admin = Blueprint("Admin", __name__, url_prefix="/admin")

app/views/auth.py
from flask import Blueprint, flash, redirect, render_template, request, session, url_for
from werkzeug.security import check_password_hash, generate_password_hash

from app.db import User, db
from app.forms import AuthForm
from app.utils import (
    generate_id,
    get_base64_encode,
    is_user_loggedin,
    user_login_required,
)

# TODO: add signup page

auth = Blueprint("Auth", __name__, url_prefix="/auth")


@auth.route("/", methods=("GET", "POST"))
def auth_index():
    if is_user_loggedin() is True:
        return redirect(url_for("Home.home_index"))

    form = AuthForm(request.form)

    if form.validate_on_submit():
        email = form.email.data
        password = form.password.data

        data = User.query.filter(User.email == email).first()

        if data:
            if check_password_hash(data.password, password) is True:
                session["session-sign-id"] = get_base64_encode(data.session_id)
                session.permanent = True
                return redirect(url_for("Home.home_index"))
            else:
                flash("Incorrect password for entered email account!", "red")
        else:
            # hashed_password = generate_password_hash(password, method="SHA256")
            hashed_password = generate_password_hash(password)
            name = email.split("@")[0][:18]
            user = User(  # type: ignore
                name=name,
                email=email,
                password=hashed_password,
                session_id=generate_id(name, email, hashed_password),
            )

            db.session.add(user)
            db.session.commit()

            flash("New account has been created, enter credentials to signin.", "green")

        return redirect(url_for(".auth_index"))

    return render_template("auth/index.html", title="Login", form=form)


@auth.route("/logout", methods=["GET", "POST"])
@user_login_required
def logout():
    if "session-sign-id" in session:
        session.pop("session-sign-id")
    session.permanent = False
    return redirect(url_for(".auth_index"))

app/views/home.py
from flask import (
    Blueprint,
    Response,
    flash,
    redirect,
    render_template,
    request,
    stream_with_context,
    url_for,
)
from sqlalchemy import func

from app.db import Statements, User, db

# from app.forms import NewStatementForm, StatementEditForm
# from app.functions import generate_string
from app.utils import get_current_user, get_current_user_balance, user_login_required

home = Blueprint("Home", __name__)


@home.route("/")
@user_login_required
def home_index():
    user = get_current_user()
    user_details = {}
    user_details["name"] = user.name
    user_details["account_balance"] = round(get_current_user_balance(), 2)
    statements = (
        db.session.query(Statements)
        .filter(Statements.user_id == 1)
        .order_by(Statements.operation_time.desc())
        .limit(5)
        .all()
    )
    user_details["statements"] = [
        {
            "desc": res.description,
            "amount": res.amount,
            "at": res.operation_time,
            "id": res.statement_id,
        }
        for res in statements
    ]
    return render_template("home/index.html", user=user_details)


@home.route("/new", methods=("GET", "POST"))
@user_login_required
def new_statement():
    form = NewStatementForm(request.form)
    if form.validate_on_submit():
        amount = form.amount.data
        description = form.description.data
        at = form.datetime_data.data
        income = form.income.data
        expense = form.expense.data

        if not income and not expense:
            flash("Cannot add statement that is neither income nor expense!", "red")
            return redirect(url_for(".new_statement"))

        amount = abs(amount)
        if expense is True:
            amount = -amount

        current_user = get_current_user()
        user_id = current_user.id

        statement = Statements(
            description=description,
            amount=amount,
            operation_time=at,
            user_id=user_id,
            statement_id=generate_string(),
        )

        db.session.add(statement)
        db.session.commit()

        flash("Statement was added to your account successfully.", "green")
        return redirect(url_for("Home.home_index"))

    return render_template("home/new_statement.html", title="New statement", form=form)

app/views/settings.py
from flask import Blueprint

from app.utils import user_login_required

settings = Blueprint("Settings", __name__, url_prefix="/settings")


@settings.route("/")
@user_login_required
def settings_index():
    return 200

app/templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    {% if title %}
    <title>{{ title }}</title>
    {% else %}
    <title>Expense-Tracker</title>
    {% endif %}

    <link rel="stylesheet" href="{{ url_for('static', filename='css/main.css') }}">

    {% block head %}
    {% endblock %}

    <script>
        function remove_message(ele){
            ele.parentElement.parentElement.removeChild(ele.parentElement)
        }
    </script>
</head>
<body>
    <div class="root">
        <header class="header" translate="no">
            Finance-Monitor
        </header>
        {% with msgs = get_flashed_messages(with_categories=true) %}
            {% if msgs %}
            <div class="messages-s">
                {% for cat, msg in msgs %}
                    <div class="msg msg-{{cat}}">
                        <span>{{msg}}</span>
                        <button type="button" class="end-btn" onclick="remove_message(this)" title="Close this message">&times;</button>
                    </div>
                {% endfor %}
            </div>
            {% endif %}
        {% endwith %}
        <div class="content">
            {% block body_before %}
            {% endblock %}
            {% block body %}
            {% endblock %}
        </div>
        {% if footer is true %}
        <div class="footer">
            <footer>
                <div class="part">
                    <div class="head">Finance-Monitor</div>
                </div>
                <div class="part">
                    <div class="body" style="display: flex;flex-direction: row; flex-wrap: wrap;">
                        <a href="#" class="btn w-btn" style="display: block;">About us</a>
                        <a href="#" class="btn w-btn" style="display: block;">Contact us</a>
                    </div>
                </div>
            </footer>
        </div>
        {% endif %}
    </div>
</body>
</html>

app/templates/home/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    {% if title %}
    <title>{{ title }}</title>
    {% else %}
    <title>Expense-Tracker</title>
    {% endif %}

    <link rel="stylesheet" href="{{ url_for('static', filename='css/main.css') }}">

    {% block head %}
    {% endblock %}

    <script>
        function remove_message(ele){
            ele.parentElement.parentElement.removeChild(ele.parentElement)
        }
    </script>
</head>
<body>
    <div class="root">
        <header class="header" translate="no">
            Finance-Monitor
        </header>
        {% with msgs = get_flashed_messages(with_categories=true) %}
            {% if msgs %}
            <div class="messages-s">
                {% for cat, msg in msgs %}
                    <div class="msg msg-{{cat}}">
                        <span>{{msg}}</span>
                        <button type="button" class="end-btn" onclick="remove_message(this)" title="Close this message">&times;</button>
                    </div>
                {% endfor %}
            </div>
            {% endif %}
        {% endwith %}
        <div class="content">
            {% block body_before %}
            {% endblock %}
            {% block body %}
            {% endblock %}
        </div>
        {% if footer is true %}
        <div class="footer">
            <footer>
                <div class="part">
                    <div class="head">Finance-Monitor</div>
                    {% comment %} <div class="body">
                        <p>&copy; 2022 - All rights reserved.</p>
                    </div> {% endcomment %}
                </div>

                <div class="part">
                    <div class="body" style="display: flex;flex-direction: row; flex-wrap: wrap;">
                        <a href="#" class="btn w-btn" style="display: block;">About us</a>
                        <a href="#" class="btn w-btn" style="display: block;">Contact us</a>
                    </div>
                </div>
            </footer>
        </div>
        {% endif %}
    </div>
</body>
</html>

app/templates/home/index.html
{% extends "base.html" %}

{% block head %}
<link rel="stylesheet" href="{{ url_for('static', filename='css/home.css') }}">
<link rel="stylesheet" href="{{ url_for('static', filename='css/statements.css') }}">
{% endblock %}

{% block body %}
<div class="shadow-card" id="expense-card">
    <div id="name">Hello, {{ user.name }}</div>
    <div id="top">
        <div class="part" style="display: flex;flex-direction: column;align-items:center;justify-content:center;">
            <div id="balance">
                <span id="currency">&#8377;</span>
                <span id="num">{{ user.account_balance }}</span>
            </div>
        </div>
        <div class="part">
            <div id="operations">
                <a class="btn-a" href="{{ url_for('Home.new_statement') }}">Add statement</a>
                <a class="btn-a" href="{{ url_for('Home.statements') }}">View statements</a>
                <a class="btn-a" href="{{ url_for('Settings.settings_index') }}">Settings</a>
            </div>
        </div>
    </div>
    <div id="bottom" class="part">
        <h1>Last statements</h1>
        <div id="statements">
            {% if user.statements %}
                {% for statement in user.statements %}
                    <a href="{{ url_for('Home.specific_statement', statement_id=statement.id) }}" class="statement">
                        <div>
                            <div class="desc">{{statement.desc}}</div>
                            <div class="at">{{statement.at}}</div>
                        </div>
                        <div class="amount">&#8377;{{statement.amount}}</div>
                    </a>
                {% endfor %}
            {% else %}
                <p>You've not added any statements yet.</p>
            {% endif %}
        </div>
    </div>
</div>
{% endblock %}

app/templates/home/new_statement.html
{% extends "base.html" %}

{% block body %}
<div class="form">
    <a href="{{ url_for('Home.home_index') }}">&lt;&lt; Back to Home</a>
    <h1>Add Statement</h1>
    <form action="{{ url_for('Home.new_statement') }}" method="post">
        {{ form.csrf_token() }}
        <div class="label">
            {{ form.amount.label }}
            {{ form.amount() }}
            {% if form.amount.errors %}
                <div class="errors">
                    {% for error in form.amount.errors %}
                        <p>{{error}}</p>
                    {% endfor %}
                </div>
            {% endif %}
        </div>
        <div class="label">
            {{ form.description.label }}
            {{ form.description() }}
            {% if form.description.errors %}
                <div class="errors">
                    {% for error in form.description.errors %}
                        <p>{{error}}</p>
                    {% endfor %}
                </div>
            {% endif %}
        </div>
        <div class="label">
            {{ form.datetime_data.label }}
            {{ form.datetime_data() }}
            {% if form.datetime_data.errors %}
                <div class="errors">
                    {% for error in form.datetime_data.errors %}
                        <p>{{error}}</p>
                    {% endfor %}
                </div>
            {% endif %}
        </div>

        {{ form.expense }}
        {{ form.income }}
    </form>
</div>
{% endblock %}